name: Close issues related to a merged PR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  closeIssueOnPrMerged:

    runs-on: ubuntu-latest

    steps:
      - name: Close issues related to a merged PR
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
